#!/bin/bash
set -e
# Variables coming from configuration
export JH_PACK_INSTALL="/blfs_root/packInstall.sh"
export JH_SRC_ARCHIVE="/sources"
export JH_SRC_SUBDIRS=""
export JH_BUILD_ROOT="/sources"
export JH_BUILD_SUBDIRS="y"
export JH_KEEP_FILES=""
unset CFLAGS
unset CXXFLAGS
unset LDFLAGS
export MAKEFLAGS="-j6"
export NINJAJOBS="6"
unset MAKELEVEL
unset MAKE_TERMOUT
unset MAKE_TERMERR
if [ -r /etc/profile ]; then source /etc/profile; fi
# End of environment
export JH_PKG_DIR=git
SRC_DIR=${JH_SRC_ARCHIVE}${JH_SRC_SUBDIRS:+/${JH_PKG_DIR}}
BUILD_DIR=${JH_BUILD_ROOT}${JH_BUILD_SUBDIRS:+/${JH_PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR
PACKAGE=git-2.37.2.tar.xz
if [[ ! -f $PACKAGE ]] ; then
  if [ -f "$JH_SRC_ARCHIVE/$PACKAGE" ] ; then
    cp "$JH_SRC_ARCHIVE/$PACKAGE" "$PACKAGE"
  else
    wget -T 30 -t 5 "https://www.kernel.org/pub/software/scm/git/git-2.37.2.tar.xz" ||
    wget -T 30 -t 5 "${JH_FTP_SERVER}svn/g/$PACKAGE"
  fi
fi
echo "2e4cb4fe7f778a9f621a735ba0585009  $PACKAGE" | md5sum -c -

PACKAGE1=git-manpages-2.37.2.tar.xz
if [[ ! -f $PACKAGE1 ]] ; then
  if [ -f "$JH_SRC_ARCHIVE/$PACKAGE1" ] ; then
    cp "$JH_SRC_ARCHIVE/$PACKAGE1" "$PACKAGE1"
  else
    wget -T 30 -t 5 "https://www.kernel.org/pub/software/scm/git/git-manpages-2.37.2.tar.xz" ||
    wget -T 30 -t 5 "${JH_FTP_SERVER}svn/g/$PACKAGE1"
  fi
fi
[ "$SRC_DIR" != "$BUILD_DIR" ] && ln -sf "$SRC_DIR/$PACKAGE1" "$BUILD_DIR"

PACKAGE1=git-htmldocs-2.37.2.tar.xz
if [[ ! -f $PACKAGE1 ]] ; then
  if [ -f "$JH_SRC_ARCHIVE/$PACKAGE1" ] ; then
    cp "$JH_SRC_ARCHIVE/$PACKAGE1" "$PACKAGE1"
  else
    wget -T 30 -t 5 "https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.37.2.tar.xz" ||
    wget -T 30 -t 5 "${JH_FTP_SERVER}svn/g/$PACKAGE1"
  fi
fi
[ "$SRC_DIR" != "$BUILD_DIR" ] && ln -sf "$SRC_DIR/$PACKAGE1" "$BUILD_DIR"

cd $BUILD_DIR
find . -maxdepth 1 -mindepth 1 -type d | xargs rm -rf

case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     JH_UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     JH_UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $JH_UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       JH_UNPACKDIR=${PACKAGE%.zip}
       unzip -d $JH_UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     JH_UNPACKDIR=$JH_PKG_DIR-build
     mkdir $JH_UNPACKDIR
     cp $SRC_DIR/$PACKAGE $JH_UNPACKDIR
     ADDITIONAL="$(find . -mindepth 1 -maxdepth 1 -type l)"
     if [ -n "$ADDITIONAL" ]; then
         cp $ADDITIONAL $JH_UNPACKDIR
     fi
     ;;
esac
export JH_UNPACKDIR
cd $JH_UNPACKDIR

./configure --prefix=/usr \
            --with-gitconfig=/etc/gitconfig \
            --with-python=python3
make
#make html
#make man
#make -k test || true
make -j1 perllibdir=/usr/lib/perl5/5.36/site_perl install
#make -j1 install-man

#make -j1 htmldir=/usr/share/doc/git-2.37.2 install-html

tar -xf ../git-manpages-2.37.2.tar.xz \
    -C /usr/share/man --no-same-owner --no-overwrite-dir
mkdir -vp   /usr/share/doc/git-2.37.2
tar   -xf   ../git-htmldocs-2.37.2.tar.xz \
      -C    /usr/share/doc/git-2.37.2 --no-same-owner --no-overwrite-dir

find        /usr/share/doc/git-2.37.2 -type d -exec chmod 755 {} \;
find        /usr/share/doc/git-2.37.2 -type f -exec chmod 644 {} \;
mkdir -vp /usr/share/doc/git-2.37.2/man-pages/{html,text}
mv        /usr/share/doc/git-2.37.2/{git*.txt,man-pages/text}
mv        /usr/share/doc/git-2.37.2/{git*.,index.,man-pages/}html

mkdir -vp /usr/share/doc/git-2.37.2/technical/{html,text}
mv        /usr/share/doc/git-2.37.2/technical/{*.txt,text}
mv        /usr/share/doc/git-2.37.2/technical/{*.,}html

mkdir -vp /usr/share/doc/git-2.37.2/howto/{html,text}
mv        /usr/share/doc/git-2.37.2/howto/{*.txt,text}
mv        /usr/share/doc/git-2.37.2/howto/{*.,}html

sed -i '/^<a href=/s|howto/|&html/|' /usr/share/doc/git-2.37.2/howto-index.html
sed -i '/^\* link:/s|howto/|&html/|' /usr/share/doc/git-2.37.2/howto-index.txt

for libdir in /lib /usr/lib $(find /opt -name lib); do
  find $libdir -name \*.la           \
             ! -path \*ImageMagick\* \
               -delete
done
ldconfig


cd $BUILD_DIR
[[ -n "$JH_KEEP_FILES" ]] || rm -rf $JH_UNPACKDIR unpacked

exit
